// Generated by CoffeeScript 1.3.3
(function() {

  $.fn.progressBar = function(progress) {
    var bar, isSetup, label, options, removeColorClasses, setup,
      _this = this;
    isSetup = function() {
      return _this.data('pb-setup') === true;
    };
    setup = function() {
      _this.html("<div class='pb-container'>              <div class='pb-progress-bar'>                <div class='pb-progress pb-transition' style='width:0%;display:none;'>                  <div class='pb-label' style='display:none;'>                  </div>                </div>              </div>            </div>");
      return _this.data('pb-setup', true);
    };
    if (!isSetup()) {
      setup();
    }
    options = {
      0: function() {
        return removeColorClasses(bar).addClass('pb-color-red');
      },
      20: function() {
        return removeColorClasses(bar).addClass('pb-color-yellow');
      },
      50: function() {
        return removeColorClasses(bar).addClass('pb-color-blue');
      },
      80: function() {
        return removeColorClasses(bar).addClass('pb-color-green');
      }
    };
    removeColorClasses = function(bar) {
      var cssClass, _i, _len, _ref;
      _ref = bar.attr('class').split(' ');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cssClass = _ref[_i];
        if (/^pb-color.*$/.test(cssClass)) {
          bar.removeClass(cssClass);
        }
      }
      return bar;
    };
    bar = $('.pb-progress', this);
    label = $('.pb-label', this);
    return $('.pb-progress', this).animate({
      width: "" + progress + "%"
    }, {
      duration: 2000,
      easing: 'swing',
      step: function(progress) {
        var transition;
        progress = Math.ceil(progress);
        if (bar.css('width') !== '0px') {
          if (bar.is(":hidden")) {
            bar.show();
          }
        }
        transition = options[progress];
        if (transition != null) {
          transition();
        }
        label.text("" + progress + "%");
        if (progress < 10) {
          if (label.is(":visible")) {
            return label.fadeOut();
          }
        } else {
          if (label.is(":hidden")) {
            return label.fadeIn();
          }
        }
      }
    });
  };

}).call(this);
